### ISSUE TITLE
More cover page tweaks

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#30]
Left: generated, Right: original

* Need "Revision 3" --> this should be an extra doc-attribute
* Spacing around "SCAP Version 1.3" needs adjustment
* NIST logo spacing -- logo should always be at bottom of the page.

<img width="1529" alt="screen shot 2019-01-09 at 12 51 09 am" src="https://user-images.githubusercontent.com/11865/50845805-b7c3b280-13a8-11e9-9d48-03bf23893479.png">

**Comment by opoudjis** [comment]
Need to get v: namespace in cover page recognised, so that VML command to position image at bottom of page can be processed.

**Comment by opoudjis** [comment]
It turns out that we are trying to emend the Word HTML exported from the intro/cover page into XHTML by passing it through Nokogiri, but because Word HTML does not put its attributes in quotes, Nokogiri fails to process namespaces in the fragment it is passed!

**Comment by opoudjis** [comment]
... Not enough: also need to get rid of HTML escapes like &nbsp;. In effect, if there are extraneous namespaces in an HTML fragment to be read in, it must already be pure XML, it cannot be tidied up by Nokogiri.

**Comment by opoudjis** [comment]
At long last resolved. Needed fixes in isodoc, to process namespaces in HTML fragments for intro/cover; fixes to metanorma-nist, so that any such fragment was strict XHTML; and fixes to html2doc postprocessing of HTML, so that it could correctly detect the VML tags involving images (v:imagedata), and not mangle other VML tags by making them `<x></x>`, or by converting their IDs to bookmarks.
