### ISSUE TITLE
Terms and definition should have fixed location, no clause numbers

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#46]
* In ISO and others, each term has a clause number, can support notes, examples, alternative terms, sources. Right now in NIST SP 800 documents the terms are represented in a simplistic glossary.
* The glossary in NIST SP 800 documents is placed in the Appendix. In other standard publications the terms and definitions section is usually a proper section.
* Proposal: Make the glossary a full fledged terms section like the others.
 
Decisions:

1. We need to have more robust glossaries that support notes, examples, alternative terms, and sources. 

2. However, we do not want add clause numbers to terms now. While this is used in ISO documents, but it has not been used in NIST pub glossaries. 

3. Also, in most cases the Glossary is placed in an Appendix (although some crypto pubs include it as a section before the technical content is introduced). It seems to fit well there (in an Appendix) and most users and authors are comfortable with it being located there.

**Comment by opoudjis** [comment]
@ronaldtse, there are two approaches to this. I know which one you're going to prefer, but I'm running them past you.

The first is to shove notes, examples, references, and the alternative term and deprecated term macros into the existing definition list structure. It will work and render with not much effort.

The second is to insist on the XML being marked up as Metanorma terms, and then to render terms for NIST like definition lists. That will involve more work on the rendering side. In order to allow terms and definitions to be an arbitrary appendix, I can make appendixes called Glossary parse like terms.

The second preserves the Metanorma semantics of terms, and the first does not. But given that the second is more work, not only in implementation but also for content authors, I want you to be sure that it is worth it. Actually, no: I want *NIST* to be sure that it's worth it. Ask them if they are likely to do any work with termbanks or other semantic processing of terms, or if this is only about rendering for them.

**Comment by ronaldtse** [comment]
@opoudjis My preferred approach is, as you can guess, the latter one. 

The second is not more work for content authors -- it makes things consistent across the Metanorma processors and is easier for the author to know one syntax than knowing two.

A person from NIST has said that they hope to have terms be "fetched" from their glossary, and to be able to cross reference terms from different documents. I take this intention to mean that the Metanorma XML should retain proper term structure.

**Comment by opoudjis** [comment]
Will have to redo the NIST exemplar document glossaries :( . Will also need to make sure that glossaries still render as definition lists.

**Comment by ronaldtse** [comment]
This will allow us (and NIST) to have more flexible terms. Will be a good thing! :wink:
